import type { Metadata } from "next";
import "./globals.css";
import ImageLoader from "./components/ImageLoader";
import Notification from "./components/Notification";
import { cinzel } from "./fonts";

export const metadata: Metadata = {
  title: "Women Clothing Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cinzel.variable}>
      <body
        className="font-cinzel antialiased"
      >
        <ImageLoader>
          {children}
          <Notification />
        </ImageLoader>
      </body>
    </html>
  );
}
